// Generated by CoffeeScript 1.7.1
(function() {
  var exports, install, jsonifier, parser;

  parser = function(model, defs) {
    var parse;
    parse = model.prototype.parse;
    return function(attrs) {
      var encoding, key;
      attrs = parse.call(this, attrs);
      for (key in defs) {
        encoding = defs[key];
        if (key in attrs && !Buffer.isBuffer(attrs[key])) {
          attrs[key] = new Buffer(attrs[key], encoding);
        }
      }
      return attrs;
    };
  };

  jsonifier = function(model, defs) {
    var toJSON;
    toJSON = model.prototype.toJSON;
    return function() {
      var attrs, encoding, key;
      attrs = toJSON.call(this);
      for (key in defs) {
        encoding = defs[key];
        if (key in attrs && Buffer.isBuffer(attrs[key])) {
          attrs[key] = attrs[key].toString(encoding);
        }
      }
      return attrs;
    };
  };

  install = function(model, defs) {
    model.prototype.parse = parser(model, defs);
    model.prototype.toJSON = jsonifier(model, defs);
    return model;
  };

  module.exports = exports = install;

  exports.parser = parser;

  exports.jsonifier = jsonifier;

}).call(this);
